name 'tohuwabohu-patch'
version '1.0.0'
source 'https://github.com/tohuwabohu/puppet-patch.git'
project_page 'https://github.com/tohuwabohu/puppet-patch'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Patch files using diffs'
description 'Manage and apply diff files on original files using the patch command'

dependency  'puppetlabs/stdlib', '4.x'
dependency  'example42/puppi', '2.x'
